import time
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from agents.red_team_agent import AutonomousRedTeamAgent
from defense.evolution_engine import EvolutionEngine
from analysis.model_security_scoring import ModelSecurityScorer
from analysis.emerging_threats import EmergingThreatAnalyzer
from analysis.threat_feed_generator import ThreatFeedGenerator
from simulation.attack_lab import AttackLab

class AutonomousLoop:
    """The central daemon executing continuous unsupervised machine learning loops. Ensures Agent autonomy globally."""
    def __init__(self):
        self.rta = AutonomousRedTeamAgent()
        self.evo = EvolutionEngine()
        self.scorer = ModelSecurityScorer()
        self.threat_analyzer = EmergingThreatAnalyzer(self.rta.db)
        self.feed_generator = ThreatFeedGenerator(self.rta.db)
        self.attack_lab = AttackLab()
        
    def start(self, interval_seconds=3600):
        print(f"[V5 Daemon] Autonomous AI Routine engaged natively. Sleep Threshold: {interval_seconds}s.")
        try:
            while True:
                print("\n=== [Autonomous Evolution Cycle Initiated] ===")
                # Cycle Phase 1: Offensive Red Team Hallucinations
                self.rta.synthesize_new_vectors(max_samples=2) # Throttling volume to cap API token burns safely
                
                # Cycle Phase 2: Sandbox execution of un-tested LLM generated bypasses
                self.attack_lab.simulate_campaign()
                
                # Cycle Phase 3: Defense Mechanism Structural Abstracting
                self.evo.evolve_defenses()
                
                # Cycle Phase 4: Spatial Pattern Recognition via DBSCAN
                self.threat_analyzer.discover_patterns()
                
                # Cycle Phase 4: Compute live Resiliency Statistics across Models natively
                self.scorer.generate_scores()
                
                # Cycle Phase 5: Flush Threat Intelligence Network Feeds
                self.feed_generator.generate_weekly_report(output_dir="reports")
                
                print(f"=== [Cycle Concluded. Next synchronization strictly at T+{interval_seconds}s] ===\n")
                time.sleep(interval_seconds)
                
        except KeyboardInterrupt:
            print("[V5 Daemon] Background loop properly interrupted internally. Shutting down agents.")

if __name__ == "__main__":
    daemon = AutonomousLoop()
    # Execute loop directly at 10 minute intervals 
    daemon.start(interval_seconds=600)
